(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-ispell-fuzzy-limit 2)
 '(ac-ispell-requires 3)
 '(elfeed-feeds
   '("http://emacs.stackexchange.com/feeds" "https://takeonrules.com/index.xml"
     ("https://podcast.unchartedx.com/feed.xml")
     ("https://notrelated.xyz/rss")
     ("https://emacstil.com/feed.xml")
     ("https://lucidmanager.org/index.xml")
     ("https://updates.orgmode.org/feed/updates")
     ("https://off-guardian.org/feed/")
     ("https://www.rebelnews.com/news.rss")
     ("https://www.westernstandardonline.com/feed/")
     ("http://feeds.feedburner.com/TheWell-readAnarchist")
     ("https://www.corbettreport.com/videorss.xml" video)
     ("https://www.corbettreport.com/wrarss.xml")
     ("https://www.corbettreport.com/articlerss.xml")
     ("https://www.corbettreport.com/flnworss.xml")
     ("https://www.corbettreport.com/propagandawatchrss.xml")
     ("https://www.corbettreport.com/solutionswatchrss.xml")
     ("https://www.corbettreport.com/qfcrss.xml")
     ("https://www.corbettreport.com/newrss.xml")
     ("https://www.reddit.com/r/DistroTube/.rss" reddit)
     ("https://www.reddit.com/r/DoomEmacs/.rss" reddit)
     ("https://www.reddit.com/r/planetemacs/.rss" reddit)
     ("https://www.reddit.com/r/emacs/.rss" reddit)
     ("https://www.bitchute.com/feeds/rss/channel/sanity-for-sweden" bitchute video)
     ("https://www.bitchute.com/feeds/rss/channel/markdice" bitchute video)
     ("https://www.bitchute.com/feeds/rss/channel/amazingpolly" bitchute video)
     ("https://odysee.com/$/rss/@BestEvidence:b" odysee video)
     ("https://odysee.com/$/rss/@GorTheMovieGod:7" odysee video)
     ("https://odysee.com/$/rss/@SaltyCracker:a" odysee video)
     ("https://odysee.com/$/rss/@ComputingForever:9" odysee video)
     ("https://odysee.com/$/rss/@AnythingGoes:2" odysee video)
     ("https://odysee.com/$/rss/@DistroTube:2" odysee video)
     ("https://odysee.com/$/rss/@corbettreport:0" odysee video)
     ("https://odysee.com/$/rss/@RobBraxmanTech:6" odysee video)
     ("https://odysee.com/$/rss/@BrodieRobertson:5" odysee video)
     ("https://odysee.com/$/rss/@academyofideas:3" odysee video)
     ("https://odysee.com/$/rss/@AfterSkool:7" odysee video)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCAiiOTio8Yu69c3XnR7nQBQ")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2RCcnTltR3HMQOYVqwmweA")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC-qh8HCLNKlGhn-jOuEd3rg")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYiI-drPAVQU74dSKVZ2Yjg")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC91V6D3nkhP89wUb9f_h17g")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCNnKprAG-MWLsk-GsbsC2BA")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCOjc2LTXq55J0HNUMvNhvYw")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCJdmdUp5BrsWsYVQUylCMLg")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC5L_M7BF5iait4FzEbwKCAg")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCTiL1q9YbrVam5nP2xzFTWQ")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC4sEmXUuWIFlxRIFBRV6VXQ")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYwVxWpjeKFWwu8TML-Te9A")
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCIMXKin1fXXCeq2UJePJEog")
     ("https://atom.io/packages.atom")
     ("https://distrowatch.com/news/news-headlines.xml")
     ("https://anchor.fm/s/a5967a8/podcast/rss")
     ("https://www.debugpoint.com/feed")
     ("https://goinglinux.com/oggpodcast.xml")
     ("https://distrowatch.com/news/dw.xml")
     ("https://www.linux-magazine.com/rss/feed/lmi_news")
     ("https://latenightlinux.com/feed/extra")
     ("https://latenightlinux.com/feed/mp3")
     ("https://distrowatch.com/news/distro/arco.xml")
     ("http://linuxscoop.com/feed/rss")
     ("https://itsfoss.com/feed/")
     ("https://ubuntupodcast.org/feed/podcast/")
     ("http://www.thelinuxlink.net/tllts/tllts.rss")
     ("https://ubuntupodcast.org/feed/")
     ("http://www.archlinux.org/feeds/news/")
     ("http://www.archlinuxuser.com/feeds/posts/default?alt=rss")
     ("http://allanmcrae.com/feed/")
     ("https://qcurtius.com/feed/")
     ("https://thepotholenews.ca/feed")
     ("https://tomluongo.me/feed/")
     ("https://ibankcoin.com/flyblog/rss")
     ("https://ibankcoin.com/rss")
     ("https://opensourcemusings.com/feed/")
     ("http://feeds.feedburner.com/OpenSourceAlternative")))
 '(org-agenda-files
   '("~/org/todo.org" "~/org/journal.org" "~/org/notes.org" "~/org/organizer.org"))
 '(package-selected-packages
   '(typit typing osm beacon ytdl elfeed-org elfeed-goodies elfeed deft page-break-lines mpv ac-capf auto-complete treemacs-evil treemacs-all-the-icons treemacs-icons-dired modus-themes dired-rainbow diredfl ac-ispell all-the-icons-dired doom-themes all-the-icons wordel rainbow-mode pandoc-mode pandoc orderless)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-level-1 ((t (:inherit outline-1 :height 1.2))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.0))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.0))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.0)))))
