(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(elfeed-feeds
   '("https://pragmaticemacs.wordpress.com/feed/"
     ("https://github.com/doomemacs/doomemacs/commits/master.atom" github)
     ("https://github.com/dvsdude2/doom/commits/main.atom" github)
     ("https://podcast.unchartedx.com/feed.xml" hist)
     ("https://notrelated.xyz/rss")
     ("https://ag91.github.io/rss.xml" emacs)
     ("https://emacstil.com/feed.xml" emacs)
     ("https://updates.orgmode.org/feed/updates" emacs)
     ("http://emacs.stackexchange.com/feeds" emacs)
     ("https://elpa.brause.cc/melpa.xml" emacs)
     ("https://off-guardian.org/feed/" news)
     ("https://www.rebelnews.com/news.rss" news)
     ("https://www.corbettreport.com/articlerss.xml")
     ("https://www.corbettreport.com/solutionswatchrss.xml")
     ("https://www.corbettreport.com/qfcrss.xml")
     ("https://www.corbettreport.com/newrss.xml")
     ("https://www.reddit.com/r/DistroTube/.rss" reddit doom)
     ("https://www.reddit.com/r/DoomEmacs/.rss" reddit doom)
     ("https://www.reddit.com/r/planetemacs/.rss" reddit emacs)
     ("https://www.reddit.com/r/emacs/.rss" reddit emacs)
     ("https://www.bitchute.com/feeds/rss/channel/sanity-for-sweden" bit video fun)
     ("https://www.bitchute.com/feeds/rss/channel/markdice" bit video fun)
     ("https://www.bitchute.com/feeds/rss/channel/amazingpolly" bit video)
     ("https://www.bitchute.com/feeds/rss/channel/Gor_Reacts" bit video fun)
     ("https://odysee.com/$/rss/@PaulJosephWatson:5" odys video news)
     ("https://odysee.com/$/rss/@BestEvidence:b" odys video real)
     ("https://odysee.com/$/rss/@GorTheMovieGod:7" odys video fun)
     ("https://odysee.com/$/rss/@SaltyCracker:a" odys video news)
     ("https://odysee.com/$/rss/@ComputingForever:9" odys video)
     ("https://odysee.com/$/rss/@AnythingGoes:2" odys video news)
     ("https://odysee.com/$/rss/@DistroTube:2" odys video doom)
     ("https://odysee.com/$/rss/@corbettreport:0" odys video)
     ("https://odysee.com/$/rss/@RobBraxmanTech:6" odys video)
     ("https://odysee.com/$/rss/@BrodieRobertson:5" odys video linux)
     ("https://odysee.com/$/rss/@academyofideas:3" odys video)
     ("https://odysee.com/$/rss/@AfterSkool:7" odys video)
     ("https://odysee.com/$/rss/@stevesteacher:0" odys video linux)
     ("https://odysee.com/$/rss/@truthstreammedia:4" odys video)
     ("https://odysee.com/$/rss/@DuckHK:b" odys video)
     ("https://odysee.com/$/rss/@TheLostHistoryChannelTKTC:0" odys video)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCAiiOTio8Yu69c3XnR7nQBQ" video yt emacs)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g" video yt sci)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2RCcnTltR3HMQOYVqwmweA" video yt emacs)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC-qh8HCLNKlGhn-jOuEd3rg" video yt)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYiI-drPAVQU74dSKVZ2Yjg" video yt fun)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC91V6D3nkhP89wUb9f_h17g" video yt fun)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCNnKprAG-MWLsk-GsbsC2BA" video yt fun)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCOjc2LTXq55J0HNUMvNhvYw" video yt fun)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCJdmdUp5BrsWsYVQUylCMLg" video yt linux)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC5L_M7BF5iait4FzEbwKCAg" video yt real)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCTiL1q9YbrVam5nP2xzFTWQ" video yt sci)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA" video yt)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UC4sEmXUuWIFlxRIFBRV6VXQ" video yt hist)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCYwVxWpjeKFWwu8TML-Te9A" video yt real)
     ("https://www.youtube.com/feeds/videos.xml?channel_id=UCIMXKin1fXXCeq2UJePJEog" video yt real)
     ("https://youtube.com/feeds/videos.xml?channel_id=UCR1D15p_vdP3HkrH8wgjQRw" video yt fun)
     ("https://youtube.com/feeds/videos.xml?channel_id=UC8CsGpP6kVNrWeBVmlJ2UyA" video yt fun)
     ("https://youtube.com/feeds/videos.xml?channel_id=UC2Stn8atEra7SMdPWyQoSLA" video yt hist)
     ("https://youtube.com/feeds/videos.xml?channel_id=UC8Q7XEy86Q7T-3kNpNjYgwA" video yt fun)
     ("https://youtube.com/feeds/videos.xml?channel_id=UCsn6cjffsvyOZCZxvGoJxGg" video yt fun)
     ("https://youtube.com/feeds/videos.xml?channel_id=UC9BMWLruGWsr1nTzFqmMfHw" video yt fun)
     ("https://youtube.com/feeds/videos.xml?channel_id=UCEq_Dr1GHvnNPQNfgOzhZ8Q" video yt fun)
     ("https://youtube.com/feeds/videos.xml?channel_id=UCBngnLwNNuEXwB6BvwZ0Ykw" video yt fun)
     ("https://distrowatch.com/news/news-headlines.xml" linux)
     ("https://anchor.fm/s/a5967a8/podcast/rss" linux)
     ("https://www.debugpoint.com/feed" linux)
     ("https://goinglinux.com/oggpodcast.xml" linux)
     ("https://distrowatch.com/news/dw.xml" linux)
     ("https://latenightlinux.com/feed/extra" linux)
     ("https://latenightlinux.com/feed/mp3" linux)
     ("https://thepotholenews.ca/feed" news)
     ("https://tomluongo.me/feed/" news)
     ("https://xkcd.com/rss.xml" fun)
     ("https://itsfoss.com/feed/" linux)
     ("https://opensourcemusings.com/feed/" linux)))
 '(package-selected-packages '(stem-reading-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-level-1 ((t (:inherit outline-1 :height 1.2))))
 '(org-level-2 ((t (:inherit outline-2 :height 1.0))))
 '(org-level-3 ((t (:inherit outline-3 :height 1.0))))
 '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
 '(org-level-5 ((t (:inherit outline-5 :height 1.0)))))
