name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - "**.mp3"
      - "**.md"
      - "**.org"
      - ".dir-locals.el"
    branches:
      - master
      - develop
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - "25.1"
          - "25.3"
          - "26.1"
          - "26.3"
          - "27.2"
          - "28.1"
          - "snapshot"
        cask_version:
          - "snapshot"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: conao3/setup-cask@master
        with:
          version: ${{ matrix.cask_version }}

      - name: lint with cask
        run: cask build
